from flask import jsonify
from app.api import info_bp

@info_bp.route('/features', methods=['GET'])
def get_features():
    #return system features for landing page
    features = [
        {
            'id': 1,
            'title': 'Malware Analysis',
            'description': 'Combines static and dynamic analysis: examine file structure, headers, and signatures while monitoring real-time behaviour in an isolated sandbox',
            'icon': 'FileSearch'
        },
        {
            'id': 2,
            'title': 'URL Analysis',
            'description': 'Scan URLs for malicious content, phishing indicators, and threat intelligence in real time',
            'icon': 'Globe'
        },
        {
            'id': 3,
            'title': 'AI-Powered Reports',
            'description': 'Get clear, actionable summaries generated by advanced AI',
            'icon': 'Brain'
        },
        {
            'id': 4,
            'title': 'Secure Isolation',
            'description': 'Complete containment prevents malware from affecting your systems',
            'icon': 'Shield'
        },
        {
            'id': 5,
            'title': 'Analysis History',
            'description': 'Track and compare previous analyses for registered users',
            'icon': 'History'
        },
        {
            'id': 6,
            'title': 'Export Reports',
            'description': 'Download detailed reports in PDF format',
            'icon': 'Download'
        }
    ]
    
    return jsonify({'features': features}), 200

@info_bp.route('/health', methods=['GET'])
def health_check():
    #Health check endpoint
    return jsonify({'status': 'healthy', 'message': 'SandBug API is running'}), 200