"""restructure schema

Revision ID: 52f1d08ec834
Revises: a2d53a6a3bc2
Create Date: 2026-03-31 18:05:24.717546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52f1d08ec834'
down_revision = 'a2d53a6a3bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('url_submitted', sa.Text(), nullable=False),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('redirect_chain', sa.JSON(), nullable=True),
    sa.Column('resolved_ip', sa.String(length=45), nullable=True),
    sa.Column('abuseipdb_score', sa.Integer(), nullable=True),
    sa.Column('gsb_threat_type', sa.String(length=100), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('threat_level', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_behaviours', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dynamic_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('sandbox_provider', sa.String(length=50), nullable=True),
    sa.Column('sandbox_sample_id', sa.String(length=100), nullable=True),
    sa.Column('execution_time', sa.Integer(), nullable=True),
    sa.Column('executed_successfully', sa.Boolean(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('processes', sa.JSON(), nullable=True),
    sa.Column('network_activity', sa.JSON(), nullable=True),
    sa.Column('file_operations', sa.JSON(), nullable=True),
    sa.Column('registry_changes', sa.JSON(), nullable=True),
    sa.Column('dropped_files', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iocs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('ioc_type', sa.String(length=30), nullable=True),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('iocs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iocs_value'), ['value'], unique=False)

    op.create_table('static_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('pe_type', sa.String(length=50), nullable=True),
    sa.Column('entropy', sa.Float(), nullable=True),
    sa.Column('is_packed', sa.Boolean(), nullable=True),
    sa.Column('is_signed', sa.Boolean(), nullable=True),
    sa.Column('imports', sa.JSON(), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('strings_extracted', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yara_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('matched_strings', sa.JSON(), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('triage_sample_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=True)
        batch_op.alter_column('risk_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_analyses_risk_level'), ['risk_level'], unique=False)
        batch_op.drop_column('file_path')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('dynamic_analysis')
        batch_op.drop_column('ai_summary')
        batch_op.drop_column('static_analysis')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('static_analysis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dynamic_analysis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_analyses_risk_level'))
        batch_op.alter_column('submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('risk_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('error_message')
        batch_op.drop_column('triage_sample_id')

    op.drop_table('yara_matches')
    op.drop_table('static_results')
    with op.batch_alter_table('iocs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iocs_value'))

    op.drop_table('iocs')
    op.drop_table('dynamic_results')
    op.drop_table('ai_reports')
    op.drop_table('url_analyses')
    # ### end Alembic commands ###
