"""Add static analysis fields to Analysis model - Sprint 4

Revision ID: a2d53a6a3bc2
Revises: 9ffbcd39c678
Create Date: 2025-01-XX XX:XX:XX.XXXXXX

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d53a6a3bc2'
down_revision = '9ffbcd39c678'
branch_labels = None
depends_on = None


def upgrade():
    # ### Sprint 4: Add new fields for static analysis ###
    
    # Add new columns (all nullable to avoid issues with existing data)
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('risk_score', sa.Integer(), nullable=True))
    
    # Set default values for existing records
    op.execute("""
        UPDATE analyses 
        SET file_path = CONCAT('uploads/', filename),
            updated_at = submitted_at,
            risk_score = 0
        WHERE file_path IS NULL
    """)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_column('risk_score')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###