"""empty message

Revision ID: a94beb710515
Revises: 52f1d08ec834
Create Date: 2026-03-31 22:18:57.589179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94beb710515'
down_revision = '52f1d08ec834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('url_analysis_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'url_analyses', ['url_analysis_id'], ['id'])

    with op.batch_alter_table('static_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publisher', sa.String(length=255), nullable=True))

    with op.batch_alter_table('url_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_result', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_analyses', schema=None) as batch_op:
        batch_op.drop_column('raw_result')

    with op.batch_alter_table('static_results', schema=None) as batch_op:
        batch_op.drop_column('publisher')

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('url_analysis_id')
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
